### ISSUE TITLE
Stderr: # _/root/sparkbit/sparkbit-cli ./sparkbit-cli.go:304: undefined: barrister.Global_insecure_ssl

### ISSUE THREAD

**Issue by Ryanmtate** [coinspark/sparkbit#6]
Hello Coinspark Team,

I am working through the instructions for the sparkbit-cli and have come across the following error:

root@PMX:~/sparkbit/sparkbit-cli# ./make.sh 
Loading IDL from: ../barrister/sparkbit_api.json
Generating autogen/sparkbit/sparkbit.go as package sparkbit
Number of parallel builds: 1

-->     linux/amd64: _/root/sparkbit/sparkbit-cli

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # _/root/sparkbit/sparkbit-cli
./sparkbit-cli.go:304: undefined: barrister.Global_insecure_ssl

mv: cannot stat ‘sparkbit-cli_*_386*’: No such file or directory
mv: cannot stat ‘sparkbit-cli_*_amd64*’: No such file or directory

Also, the same error occurs when I execute:

go run sparkbit-cli.go

root@PMX:~/sparkbit/sparkbit-cli# go run sparkbit-cli.go 
# command-line-arguments
./sparkbit-cli.go:304: undefined: barrister.Global_insecure_ssl

------

Not sure if this is a bug or if I am missing a step in the instructions.

My go version: go version go1.3.3 linux/amd64

I am grateful for any advice you can provide. Thanks in advance.

Best,

Ryan

**Comment by bitcartel** [comment]
Hi Ryan,

Thanks for spotting this.

go get github.com/coopernurse/barrister-go

In $GOPATH where the src has been downloaded, you want to create a branch: tlsconfig

git checkout -b tlsconfig

Add the patched version as a remote source e.g.:

git remote set-url bitcartelpatch https://github.com/bitcartel/barrister-go

Get the code for branch tlsconfig

git pull bitcartelpatch

Finally, rebuild:

go build github.com/coopernurse/barrister-go

Let me know if this helps.  Thanks.

**Comment by Ryanmtate** [comment]
Hi bitcartel,

Thanks for your prompt reply.

I followed your instructions, however unfortunately the same problem does seem to persist after rebuilding the barrister-go tlsconfig branch.

**Comment by bitcartel** [comment]
Hi Ryan,

$GOPATH/src/github.com/coopernurse/barrister-go should be on this commit:
973854065b6d7430450b745ee0eb0072979ff6ea

Also try cleaning before building:
go clean github.com/coopernurse/barrister-go
go build github.com/coopernurse/barrister-go

Let me know how you get on, thanks.

**Comment by Ryanmtate** [comment]
Hi Bitcartel,

Thanks for the email. The error appears to have been solved. I will confirm tomorrow when I proceed!

Thanks Again!

Ryan

**Comment by Ryanmtate** [comment]
Hi Bitcartel,

This issue appears to be solved in the latest steps-- Thanks.

**Comment by Ryanmtate** [comment]
Closing, however I had to 'go get' 3 additional packages not listed in the instructions when running ./make.sh

Error message provided list of necessary packages.
